
---
- name: Install apache and upload web page
  hosts: all
  become: yes


  vars: 
    source_file: index.html
    destin_file: /var/www/html

  tasks:
  - name: Check linux version
    debug:
       var: ansible_os_family
  
  - block:    #============Debian==============
     - name: install apache web server for debian
       apt: 
         name: apache2
         state: latest

     - name: uplod web page Debian
       copy:
         src: "{{ source_file }}"
         dest: "{{ destin_file }}"
         mode: 0555
       notify:
          - Restart Apache Debian

     - name: start web server and enabled Debian
       service:
         name: apache2
         state: started
         enabled: yes
    
    when: ansible_os_family=="Debian"


  - block:   #==============RedHat=========

     - name: install apache web server for redHat
       yum:
         name: httpd
         state: latest


     - name: uplod web page RedHat
       copy:
         src: "{{ source_file }}"
         dest: "{{ destin_file }}"
         mode: 0555
       notify:
          - Restart Apache RedHat
   
     - name: staret web server and enabled RedHat
       service: 
          name: httpd
          state: started
          enabled: yes
   
    when: ansible_os_family=="RedHat"



  handlers:
    - name: Restart Apache Debian
      service:
         name: apache2
         state: restarted 

    - name: Restart Apache RedHat
      service:
         name: httpd
         state: restarted
